Repository TownyAdvanced/SiegeWar, pull requests merged in 2021-01, with the labels that each got.

#12 Adds internal support for Dynmap-Towny features present in Goosius' fork of Dynmap-Towny.
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
  src/main/resources/Changelog.txt
  src/main/resources/plugin.yml
Labels: enhancement

#20 Added: /swa siege & /swa town commands.
  src/main/java/com/gmail/goosius/siegewar/Messaging.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
  src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java
  src/main/resources/english.yml
  src/main/resources/plugin.yml
Labels: enhancement

#22 Fixed revolt feature to apply to all towns
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
  src/main/resources/english.yml
Labels: bug

#24 Fix peacefuldays metadata being added when it shouldn't.
  src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java
Labels: bug

#23 Deprecate changelog.txt.
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/resources/Changelog.txt
Labels: enhancement

#29 Make siegezones cylindrical
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
Labels: enhancement

#27 Adds Siege#getTimeRemaining() and removes two methods that did similar.
  src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java
  src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
Labels: enhancement

#26 Adds a translatable name to the SiegeStatus enum.
  src/main/java/com/gmail/goosius/siegewar/enums/SiegeStatus.java
  src/main/resources/english.yml
Labels: enhancement

#25 Add siege status to sieges on dynmap.
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
  src/main/resources/english.yml
Labels: enhancement

#32 Fix setCaptured and setPlundered.
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
Labels: bug

#33 Bump min. Towny version to 0.96.5.15
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
Labels: enhancement

#34 Finish TODO regarding using new setCancellationMsg()
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java
Labels: enhancement

#40 add UpdateHUDs to PlayerDeath
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
Labels: enhancement

#41 Changed terminology of "tactical invisibility" to "map sneaking"
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/tasks/DynmapTask.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDynmapUtil.java
Labels: enhancement

#46 Update link to license in pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#47 Drop the required MC version down to 1.13
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarPointsUtil.java
Labels: bug

#45 Negative item durability fix
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
  src/main/resources/english.yml
Labels: bug

#50 Change counter-attack booster default to active
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarPointsUtil.java
Labels: enhancement

#53 Fixes for occupied town surrender & wall banners
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/resources/english.yml
Labels: bug

#54 Inventory degrade fix.
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
Labels: bug

#28 Punishes players who are not participating in the siege with war sick…
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
  src/main/resources/english.yml
Labels: enhancement

#62 Switch to using Town.save()
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java
  src/main/java/com/gmail/goosius/siegewar/metadata/MetaDataUtil.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Labels: enhancement

#61 Fix towns having pvp and explosions forced on
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
Labels: bug

#64 Fix ArrayOutOfBounds on empty /sw nation command.
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
Labels: bug

#65 Fix sending shutting down messages twice.
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
Labels: bug

#68 Fix config not properly reloading 4 variables.
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
Labels: bug

#69 Adjusted default config value of max sieges per nation to 3
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: enhancement

#74 Fix hud permission node not being give to everyone by default.
  src/main/resources/plugin.yml
Labels: bug

#75 Adjusted default config for map sneak combos
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: enhancement

#76 Adjusted guardian town requirement
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Labels: enhancement

#77 Config blurb updates
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Labels: enhancement

#81 Fix calling on missing language string.
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
Labels: bug

#82 Add free nation choice for isolated peaceful towns
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
  src/main/resources/english.yml
Labels: enhancement

#87 Bump required version number to 0.96.7.0.
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
Labels: enhancement

#88 Bump SiegeWar version number for release.
  pom.xml
  src/main/resources/english.yml
  src/main/resources/french.yml
Labels: enhancement

#91 Disable nation perms when town is invaded
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/AttackTown.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
Labels: enhancement
