Repository TownyAdvanced/SiegeWar, pull requests merged in 2022-04, with the labels that each got.

#523 Add Siegezone Proximity Caching
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattlefieldObserverUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
Labels: enhancement

#524 Pvp unprotection configs
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
Labels: enhancement

#525 Set winner takes all to be false by default
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: enhancement

#530 Tactical Siege-Zone Improvements
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#533 Fixed double death points when logging out
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
Labels: bug

#537 Added Cap-Zone option to trap mitigation
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#541 Removed some remaining bat-observer stuff
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
Labels: bug

#542 Trap mitigation tweak
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
Labels: enhancement

#550 Re-add battle session scheduler
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
Labels: enhancement

#546 Add configurable Trap-Warfare-Mitigation radius
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#553 Fix for death-message stack overflow
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: bug

#554 Update README.md
  README.md
Labels: enhancement

#558 Clean up unused imports, suppress unused methods that may return.
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerWin.java
  src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderWin.java
  src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
Labels: bug, enhancement
