Repository TownyAdvanced/SiegeWar, pull requests merged in 2022-03, with the labels that each got.

#482 Mitigate Claim Hiding (and change Peaceful terminology)
  README.md
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarPlotEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarTownUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
  src/main/resources/english.yml
  src/main/resources/french.yml
Labels: enhancement

#483 Automatic config field migration
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/utils/MigrationUtil.java
Labels: enhancement

#484 POM update to 0.7.9 and readme update
  README.md
  pom.xml
Labels: documentation

#485 Cannons Integration - added new rule to improve gameplay
  src/main/java/com/gmail/goosius/siegewar/integration/cannons/CannonsListener.java
  src/main/resources/english.yml
  src/main/resources/french.yml
Labels: enhancement

#488 Changed map hiding config default to false
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: enhancement

#489 Fxed banner cap boss bars not disappearing
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
Labels: bug

#490 Deal with pvp toggle
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
Labels: enhancement

#486 Add multi-language support to SiegeWar.
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/Messaging.java
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarNationAddonCommand.java
  src/main/java/com/gmail/goosius/siegewar/enums/SiegeSide.java
  src/main/java/com/gmail/goosius/siegewar/enums/SiegeStatus.java
  src/main/java/com/gmail/goosius/siegewar/enums/SiegeType.java
  src/main/java/com/gmail/goosius/siegewar/hud/SiegeWarHud.java
  src/main/java/com/gmail/goosius/siegewar/integration/cannons/CannonsIntegration.java
  src/main/java/com/gmail/goosius/siegewar/integration/cannons/CannonsListener.java
  src/main/java/com/gmail/goosius/siegewar/integration/dynmap/DynmapIntegration.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarActionListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarStatusScreenListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/metadata/TownMetaDataController.java
  src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
  src/main/java/com/gmail/goosius/siegewar/objects/SiegeCamp.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/AbandonAttack.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/InvadeTown.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullyRevolt.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PeacefullySubvertTown.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlayerDeath.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlunderTown.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/StartConquestSiege.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/StartLiberationSiege.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/StartRevoltSiege.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/StartSuppressionSiege.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderDefence.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/settings/Translation.java
  src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerTimedWin.java
  src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderTimedWin.java
  src/main/java/com/gmail/goosius/siegewar/utils/BossBarUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/PermissionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeCampUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattlefieldObserverUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarImmunityUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarWallBreachUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
  src/main/resources/global.yml
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#491 Banner control reversal update
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#492 Terminology update: Siegecamps to Siege-Assembles
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/utils/MigrationUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: documentation

#494 Remove Battle Session Scheduler
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/BookUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/BossBarUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/MigrationUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#498 Add config/townyperms migration for improved drag-and-drop upgrades.
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/settings/migrator/ConfigMigrator.java
  src/main/java/com/gmail/goosius/siegewar/settings/migrator/MigrationType.java
  src/main/java/com/gmail/goosius/siegewar/settings/migrator/VersionDeserializer.java
  src/main/java/com/gmail/goosius/siegewar/utils/MigrationUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSiegeCompletionUtil.java
  src/main/resources/config-migration.json
Labels: bug, enhancement

#499 Wall Breaching - Remove banner cap requirement for bonus
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarWallBreachUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#503 Sieged town logout prevention
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarScoringUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#508 Anti-Block-Glitching
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBlockUtil.java
Labels: enhancement

#506 Refactor: Capping Limiter -> Siege Attendance Limiter
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/integration/cannons/CannonsListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/metadata/ResidentMetaDataController.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNotificationUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#507 Backend war sickness cleanup
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/tasks/SiegeWarTimerTaskController.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/TownPeacefulnessUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/lang/fr-FR.yml
Labels: enhancement

#509 Readme Update
  README.md
Labels: documentation

#513 Scheduler method fix
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
Labels: bug

#516 Enable non-participant punish feature by default
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: enhancement

#514 Misc Bug Fixes
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSicknessUtil.java
Labels: bug

#518 fix for attendance limiter culling
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
Labels: bug

#512 Trap mitigation improvement
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/DestroyBlock.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/PlaceBlock.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBannerControlUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement
