Repository TownyAdvanced/SiegeWar, pull requests merged in 2022-05, with the labels that each got.

#560 Global Domination Awards
  README.md
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarNationEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/metadata/NationMetaDataController.java
  src/main/java/com/gmail/goosius/siegewar/objects/ArtefactOffer.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarNationUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#565 Make HUD tab-prompt show only active sieges
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
Labels: enhancement

#564 Update README.md
  README.md
Labels: documentation

#573 Artefact Expiry
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#575 Fixed Artefact Explode not damaging holder
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
Labels: bug

#577 Lang file version bump
  src/main/resources/lang/en-US.yml
Labels: documentation

#579 Add Usable Artefact Suite
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
  src/main/resources/config-migration.json
Labels: enhancement

#584 Optimize artefact check
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
Labels: enhancement

#585 Added Artefact translations
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/resources/config-migration.json
  src/main/resources/lang/en-US.yml
Labels: enhancement

#589 Domination awards event
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
  src/main/java/com/gmail/goosius/siegewar/events/GlobalDominationAwardsEvent.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
Labels: enhancement

#590 Fix for unknown method error
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
Labels: bug

#596 Improvement to artefact stacking
  src/main/java/com/gmail/goosius/siegewar/objects/ArtefactOffer.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
Labels: enhancement

#593 Add Custom Artefact effects
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/events/ArtefactConsumeItemEvent.java
  src/main/java/com/gmail/goosius/siegewar/events/ArtefactDamageEntityEvent.java
  src/main/java/com/gmail/goosius/siegewar/events/ArtefactThrownPotionEvent.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarArtefactListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/Settings.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#601 Auto-apply the arrow of doom fix
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: bug

#602 Artefact Balancing Updates
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: enhancement

#603 Add Antimatter Potion & Fix Trident of Zeus
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarArtefactListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/resources/lang/en-US.yml
Labels: bug, enhancement

#606 Add Poison blades
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarArtefactListener.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDominationAwardsUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#608 Artefact Config Guide
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
Labels: documentation
