Repository TownyAdvanced/SiegeWar, pull requests merged in 2023-07, with the labels that each got.

#856 Battle Commanders / Mobile Spawn Points
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
  src/main/java/com/gmail/goosius/siegewar/enums/SiegeWarPermissionNodes.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarBukkitEventListener.java
  src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleCommanderUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarDistanceUtil.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarSpawnUtil.java
  src/main/resources/lang/en-US.yml
  src/main/resources/plugin.yml
Labels: enhancement

#859 Hotfix for battle commanders assignment
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleCommanderUtil.java
Labels: bug

#863 Remove hard dependancy on TC
  pom.xml
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyChatEventListener.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarTownyEventListener.java
Labels: bug

#866 Added logic to block HUD in folia
  src/main/java/com/gmail/goosius/siegewar/SiegeWar.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarCommand.java
  src/main/resources/lang/en-US.yml
Labels: bug

#865 Added logic so that money is not calculated if economy is missing
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
Labels: bug

#868 POM update to 2.7.0
  pom.xml
Labels: enhancement

#869 New Crowdin updates
  src/main/resources/lang/de-DE.yml
  src/main/resources/lang/es-AR.yml
  src/main/resources/lang/es-ES.yml
  src/main/resources/lang/fr-FR.yml
  src/main/resources/lang/it-IT.yml
  src/main/resources/lang/ru-RU.yml
  src/main/resources/lang/tl-PH.yml
  src/main/resources/lang/tr-TR.yml
  src/main/resources/lang/vi-VN.yml
Labels: enhancement

#871 SiegeRemoveEvent and punctuation fixes
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/events/SiegeRemoveEvent.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#876 New Crowdin updates
  src/main/resources/lang/de-DE.yml
  src/main/resources/lang/es-AR.yml
  src/main/resources/lang/es-ES.yml
  src/main/resources/lang/fr-FR.yml
  src/main/resources/lang/it-IT.yml
  src/main/resources/lang/ru-RU.yml
  src/main/resources/lang/tl-PH.yml
  src/main/resources/lang/tr-TR.yml
  src/main/resources/lang/vi-VN.yml
Labels: documentation

#877 New Crowdin updates
  src/main/resources/lang/vi-VN.yml
Labels: documentation

#879 Improve Accuracy of Money Warnings
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarMoneyUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement

#880 New Crowdin updates
  src/main/resources/lang/de-DE.yml
  src/main/resources/lang/es-AR.yml
  src/main/resources/lang/es-ES.yml
  src/main/resources/lang/fr-FR.yml
  src/main/resources/lang/it-IT.yml
  src/main/resources/lang/ru-RU.yml
  src/main/resources/lang/tl-PH.yml
  src/main/resources/lang/tr-TR.yml
  src/main/resources/lang/vi-VN.yml
Labels: documentation

#875 Discord webhook
  src/main/java/com/gmail/goosius/siegewar/SiegeController.java
  src/main/java/com/gmail/goosius/siegewar/command/SiegeWarAdminCommand.java
  src/main/java/com/gmail/goosius/siegewar/events/BattleSessionEndedEvent.java
  src/main/java/com/gmail/goosius/siegewar/events/BattleSessionStartedEvent.java
  src/main/java/com/gmail/goosius/siegewar/events/SiegeCampStartEvent.java
  src/main/java/com/gmail/goosius/siegewar/events/SiegeEndEvent.java
  src/main/java/com/gmail/goosius/siegewar/events/SiegeRemoveEvent.java
  src/main/java/com/gmail/goosius/siegewar/events/SiegeWarStartEvent.java
  src/main/java/com/gmail/goosius/siegewar/listeners/SiegeWarSelfListener.java
  src/main/java/com/gmail/goosius/siegewar/objects/Siege.java
  src/main/java/com/gmail/goosius/siegewar/playeractions/SurrenderDefence.java
  src/main/java/com/gmail/goosius/siegewar/settings/ConfigNodes.java
  src/main/java/com/gmail/goosius/siegewar/settings/SiegeWarSettings.java
  src/main/java/com/gmail/goosius/siegewar/timeractions/AttackerTimedWin.java
  src/main/java/com/gmail/goosius/siegewar/timeractions/DefenderTimedWin.java
  src/main/java/com/gmail/goosius/siegewar/utils/DiscordWebhook.java
  src/main/java/com/gmail/goosius/siegewar/utils/SiegeWarBattleSessionUtil.java
  src/main/resources/lang/en-US.yml
Labels: enhancement
